// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FastWork.Entities;

[Table("applications")]
[Index("CandidateId", Name = "idx_applications_candidate_id")]
[Index("JobId", Name = "idx_applications_job_id")]
public partial class Application
{
    [Key]
    [Column("application_id")]
    public Guid ApplicationId { get; set; }

    [Column("job_id")]
    public Guid? JobId { get; set; }

    [Column("candidate_id")]
    public Guid? CandidateId { get; set; }

    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("about")]
    public string About { get; set; }

    [Column("interview_type")]
    [StringLength(50)]
    public string InterviewType { get; set; }

    [Column("applied_at", TypeName = "datetime")]
    public DateTime? AppliedAt { get; set; }

    [ForeignKey("CandidateId")]
    [InverseProperty("Applications")]
    public virtual Candidate Candidate { get; set; }

    [ForeignKey("JobId")]
    [InverseProperty("Applications")]
    public virtual Job Job { get; set; }

    [InverseProperty("Application")]
    public virtual Payment Payment { get; set; }
}