// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FastWork.Entities;

[Table("companies")]
[Index("RecruiterId", Name = "UQ__companie__42ABA25659E2F898", IsUnique = true)]
public partial class Company
{
    [Key]
    [Column("company_id")]
    public Guid CompanyId { get; set; }

    [Column("recruiter_id")]
    public Guid? RecruiterId { get; set; }

    [Required]
    [Column("company_name")]
    [StringLength(100)]
    public string CompanyName { get; set; }

    [Column("website")]
    [StringLength(255)]
    public string Website { get; set; }

    [Column("logo_file_id")]
    public Guid? LogoFileId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    [ForeignKey("LogoFileId")]
    [InverseProperty("Companies")]
    public virtual File LogoFile { get; set; }

    [ForeignKey("RecruiterId")]
    [InverseProperty("Company")]
    public virtual User Recruiter { get; set; }
}