// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FastWork.Entities;

[Table("cv_details")]
[Index("CandidateId", Name = "idx_cv_details_candidate_id")]
public partial class CvDetail
{
    [Key]
    [Column("cv_id")]
    public Guid CvId { get; set; }

    [Column("candidate_id")]
    public Guid? CandidateId { get; set; }

    [Required]
    [Column("full_name")]
    [StringLength(100)]
    public string FullName { get; set; }

    [Column("contact_email")]
    [StringLength(100)]
    public string ContactEmail { get; set; }

    [Column("contact_phone")]
    [StringLength(20)]
    public string ContactPhone { get; set; }

    [Column("birth_date")]
    public DateOnly? BirthDate { get; set; }

    [Column("education")]
    public string Education { get; set; }

    [Column("experience")]
    public string Experience { get; set; }

    [Column("skills")]
    public string Skills { get; set; }

    [Column("portfolio_url")]
    [StringLength(255)]
    public string PortfolioUrl { get; set; }

    [Column("description")]
    public string Description { get; set; }

    [Column("position")]
    [StringLength(100)]
    public string Position { get; set; }

    [Column("field")]
    [StringLength(100)]
    public string Field { get; set; }

    [Column("languages")]
    [StringLength(255)]
    public string Languages { get; set; }

    [Column("desired_salary")]
    [StringLength(50)]
    public string DesiredSalary { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("updated_at", TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    [ForeignKey("CandidateId")]
    [InverseProperty("CvDetails")]
    public virtual Candidate Candidate { get; set; }
}