// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FastWork.Entities;

[Table("jobs")]
[Index("RecruiterId", Name = "idx_jobs_recruiter_id")]
public partial class Job
{
    [Key]
    [Column("job_id")]
    public Guid JobId { get; set; }

    [Column("recruiter_id")]
    public Guid? RecruiterId { get; set; }

    [Column("company_id")]
    public Guid? CompanyId { get; set; }

    [Column("subscription_id")]
    public Guid? SubscriptionId { get; set; }

    [Column("category_id")]
    public Guid? CategoryId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(100)]
    public string Title { get; set; }

    [Column("position")]
    [StringLength(100)]
    public string Position { get; set; }

    [Column("type")]
    [StringLength(50)]
    public string Type { get; set; }

    [Required]
    [Column("description")]
    public string Description { get; set; }

    [Column("job_details")]
    public string JobDetails { get; set; }

    [Column("requirements")]
    public string Requirements { get; set; }

    [Column("experience")]
    public string Experience { get; set; }

    [Column("benefits")]
    public string Benefits { get; set; }

    [Column("salary", TypeName = "decimal(10, 2)")]
    public decimal Salary { get; set; }

    [Column("company_name")]
    [StringLength(100)]
    public string CompanyName { get; set; }

    [Column("contact_phone")]
    [StringLength(20)]
    public string ContactPhone { get; set; }

    [Column("location")]
    [StringLength(100)]
    public string Location { get; set; }

    [Column("duration")]
    [StringLength(50)]
    public string Duration { get; set; }

    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("posted_at", TypeName = "datetime")]
    public DateTime? PostedAt { get; set; }

    [Column("is_urgent")]
    public bool? IsUrgent { get; set; }

    [InverseProperty("Job")]
    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    [ForeignKey("CategoryId")]
    [InverseProperty("Jobs")]
    public virtual Category Category { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("Jobs")]
    public virtual Company Company { get; set; }

    [InverseProperty("Job")]
    public virtual ICollection<Invitation> Invitations { get; set; } = new List<Invitation>();

    [ForeignKey("RecruiterId")]
    [InverseProperty("Jobs")]
    public virtual Recruiter Recruiter { get; set; }

    [ForeignKey("SubscriptionId")]
    [InverseProperty("Jobs")]
    public virtual Subscription Subscription { get; set; }

    [ForeignKey("JobId")]
    [InverseProperty("Jobs")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}