// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FastWork.Entities;

[Table("recruiters")]
[Index("UserId", Name = "UQ__recruite__B9BE370E94EF86F8", IsUnique = true)]
public partial class Recruiter
{
    [Key]
    [Column("recruiter_id")]
    public Guid RecruiterId { get; set; }

    [Column("user_id")]
    public Guid? UserId { get; set; }

    [Column("company_type")]
    [StringLength(50)]
    public string CompanyType { get; set; }

    [Column("scale")]
    [StringLength(50)]
    public string Scale { get; set; }

    [Column("contact_phone")]
    [StringLength(20)]
    public string ContactPhone { get; set; }

    [Column("verified")]
    public bool? Verified { get; set; }

    [InverseProperty("Recruiter")]
    public virtual ICollection<Invitation> Invitations { get; set; } = new List<Invitation>();

    [InverseProperty("Recruiter")]
    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();

    [InverseProperty("Recruiter")]
    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();

    [ForeignKey("UserId")]
    [InverseProperty("Recruiter")]
    public virtual User User { get; set; }
}