// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FastWork.Entities;

[Table("tags")]
[Index("Name", Name = "UQ__tags__72E12F1B77600626", IsUnique = true)]
public partial class Tag
{
    [Key]
    [Column("tag_id")]
    public Guid TagId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [ForeignKey("TagId")]
    [InverseProperty("Tags")]
    public virtual ICollection<Job> Jobs { get; set; } = new List<Job>();
}