// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FastWork.Entities;

[Table("work_history")]
[Index("CandidateId", Name = "idx_work_history_candidate_id")]
public partial class WorkHistory
{
    [Key]
    [Column("history_id")]
    public Guid HistoryId { get; set; }

    [Column("candidate_id")]
    public Guid? CandidateId { get; set; }

    [Column("date")]
    public DateOnly Date { get; set; }

    [Required]
    [Column("content")]
    public string Content { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CandidateId")]
    [InverseProperty("WorkHistories")]
    public virtual Candidate Candidate { get; set; }
}