// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Entities;

[Table("candidates")]
[Index("UserId", Name = "UQ__candidat__B9BE370E1C8D5C72", IsUnique = true)]
public partial class Candidate
{
    [Key]
    [Column("candidate_id")]
    public Guid CandidateId { get; set; }

    [Column("user_id")]
    public Guid? UserId { get; set; }

    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("gender")]
    [StringLength(50)]
    public string Gender { get; set; }

    [Column("education")]
    [StringLength(50)]
    public string Education { get; set; }

    [Column("income_range")]
    [StringLength(50)]
    public string IncomeRange { get; set; }

    [Column("verified")]
    public bool? Verified { get; set; }

    [Column("featured")]
    public bool? Featured { get; set; }

    [InverseProperty("Candidate")]
    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();

    [InverseProperty("Candidate")]
    public virtual ICollection<CvDetail> CvDetails { get; set; } = new List<CvDetail>();

    //[InverseProperty("Candidate")]
    //public virtual ICollection<File> Files { get; set; } = new List<File>();

    [InverseProperty("Candidate")]
    public virtual ICollection<Invitation> Invitations { get; set; } = new List<Invitation>();

    [ForeignKey("UserId")]
    [InverseProperty("Candidate")]
    public virtual User User { get; set; }

    [InverseProperty("Candidate")]
    public virtual ICollection<WorkHistory> WorkHistories { get; set; } = new List<WorkHistory>();
}