// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Entities;

[Table("files")]
public partial class File
{
    [Key]
    [Column("file_id")]
    public Guid FileId { get; set; }

    //[Column("candidate_id")]
    //public Guid? CandidateId { get; set; }

    [Required]
    [Column("file_name")]
    [StringLength(255)]
    public string FileName { get; set; }

    [Column("file_type")]
    [StringLength(50)]
    public string FileType { get; set; }

    [Column("file_data")]
    public byte[] FileData { get; set; }

    [Column("content_type")]
    [StringLength(100)]
    public string ContentType { get; set; }

    [Column("upload_date", TypeName = "datetime")]
    public DateTime? UploadDate { get; set; }

    //[ForeignKey("CandidateId")]
    //[InverseProperty("Files")]
    //public virtual Candidate Candidate { get; set; }

    [InverseProperty("LogoFile")]
    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    [InverseProperty("CvFile")]
    public virtual ICollection<User> UsersWithCvFile { get; set; } = new List<User>();
}