// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Entities;

[Table("ratings")]
[Index("ReviewerId", Name = "idx_ratings_reviewer_id")]
public partial class Rating
{
    [Key]
    [Column("rating_id")]
    public Guid RatingId { get; set; }

    [Column("reviewer_id")]
    public Guid? ReviewerId { get; set; }

    [Column("rating")]
    public int? Rating1 { get; set; }

    [Column("comment")]
    public string Comment { get; set; }

    [Column("contributed_comment")]
    public string ContributedComment { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("ReviewerId")]
    [InverseProperty("Ratings")]
    public virtual User Reviewer { get; set; }
}