// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Repo.Entities;

[Table("subscriptions")]
public partial class Subscription
{
    [Key]
    [Column("subscription_id")]
    public Guid SubscriptionId { get; set; }

    [Column("user_id")]
    public Guid? UserId { get; set; }

    [Column("plan")]
    [StringLength(50)]
    public string Plan { get; set; }

    [Column("subtitle")]
    [StringLength(255)]
    public string Subtitle { get; set; }

    [Column("duration_days")]
    public int DurationDays { get; set; }

    [Column("is_activated")]
    public bool? IsActivated { get; set; }

    [Column("price", TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    [Column("original_price", TypeName = "decimal(10, 2)")]
    public decimal? OriginalPrice { get; set; }

    [Column("features")]
    public string Features { get; set; }

    [Column("start_date", TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column("end_date", TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Subscription")]
    public virtual User User { get; set; }
}